version: '3.7'

services:

  portal:
    container_name: horse_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8088:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  sonarqube:
    container_name: "sonarqube-container"        
    image: "sonarqube:8.9.3-community"
    volumes:
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/data:/opt/sonarqube/data
    expose:
      - "9000"
    ports:
      - "9000:9000"